### ISSUE TITLE
Issue in Python 3

### ISSUE THREAD

**Issue by CannonballSkippy** [jansenicus/vtt-to-srt.py#1]
I get an error when I try to convert this file to SRT: 

[https://gist.github.com/anonymous/26961e0be61f30d477c2307d101e4633](https://gist.github.com/anonymous/26961e0be61f30d477c2307d101e4633)

It seems this does not work in Python 3 😕  I would vermy much like to use it!
```
C:\Users\username\Desktop\test>python S:\OneDrive\scripts\python\vtt-to-srt.py\vtt-to-srt.py 00001.vtt new.srt
  File "S:\OneDrive\scripts\python\vtt-to-srt.py\vtt-to-srt.py", line 56
    print "file created: " + strNamaFile + "\n"
                         ^
SyntaxError: Missing parentheses in call to 'print'

C:\Users\username\Desktop\test>
```

**Comment by heniotierra** [comment]
Python 3 version can be found at  https://github.com/0um/vtt-to-srt.py
