### ISSUE TITLE
Como usa no linux...

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [jansenicus/vtt-to-srt.py#15]
python from vtt_to_srt import vtts_to_srt path = '/home/jr/Videos/legendas/ vtts_to_srt(path, rec = True)

python vtt_to_srt.py3 /home/jr/Videos/legendas/ [-r]

Obrigado..

**Comment by heniotierra** [comment]
Como diz a documentação no README, se for usar como lib:

```
from vtt_to_srt import vtts_to_srt 

path = '/home/jr/Videos/legendas/' 
vtts_to_srt(path, rec = True)
```
Claro que para isso vc tem que isntalar a lib primeiro no seu sistema, e para isso seguir as instruções de instalação tbm no README.

Mas vc pode usar direto do terminal tbm.
