### ISSUE TITLE
Not Stripping/Converting Metadata

### ISSUE THREAD

**Issue by agret** [jansenicus/vtt-to-srt.py#9]
The VTT file:
```
WEBVTT

0
00:01.760 --> 00:04.640 position:50% align:middle size:80%
<c.box><c.yellow.bg_black>(ALARM BEEPS)</c></c>```

1
00:08.080 --> 00:12.280 position:50% align:middle size:80%
<c.box><c.cyan.bg_black>('THE LOVECATS' BY THE CURE PLAYS)</c></c>
```

The generated SRT file:
```
00:01,760 --> 00:04,640 position:50% align:middle size:80%
<c.box><c.yellow.bg_black>(ALARM BEEPS)</c></c>

00:08,080 --> 00:12,280 position:50% align:middle size:80%
<c.box><c.cyan.bg_black>('THE LOVECATS' BY THE CURE PLAYS)</c></c>
```

This file is invalid and doesn't load properly in SRT playback, it should be:
```
00:01,760 --> 00:04,640
(ALARM BEEPS)

00:08,080 --> 00:12,280
'THE LOVECATS' BY THE CURE PLAYS)
```

**Comment by heniotierra** [comment]
You're right. I think stripping these stuff should solve the problem.

**Comment by Vuochnai** [comment]
I think should be like this:

`1
00:01,760 --> 00:04,640
(ALARM BEEPS)

2
00:08,080 --> 00:12,280
'THE LOVECATS' BY THE CURE PLAYS)

3
==================`

**Comment by Vuochnai** [comment]
I think should be like this:

> 

1
00:01,760 --> 00:04,640
(ALARM BEEPS)

2
00:08,080 --> 00:12,280
'THE LOVECATS' BY THE CURE PLAYS)

3
==================

**Comment by channchetra** [comment]
I think should be like this:

`1
00:01,760 --> 00:04,640
(ALARM BEEPS)

2
00:08,080 --> 00:12,280
'THE LOVECATS' BY THE CURE PLAYS)

3
==================`

**Comment by heniotierra** [comment]
Fixed. Thank you guys!
